import type { Metadata } from "next";
import { Fraunces } from "next/font/google";
import { connectDb } from "@/config/db";
import "./globals.css";

const frauncesSans = Fraunces({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectDb(); //testing db connection
  return (
    <html lang="en">
      <body className={`${frauncesSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
